In [1]:
import pandas as pd
df = pd.read_csv("don-gerard.csv")
df

,CommitteeID,CommitteeName,ContributedBy,RcvdDate,Amount,LoanAmount,Occupation,Employer,Address1,Address2,...,VendorAddress1,VendorAddress2,VendorCity,VendorState,VendorZip,DocName,Election,RptPdBegDate,RptPdEndDate,FiledRcvdDate
0,22970,Friends of Don Gerard,"Adams, George",3/18/2015,250.0,0,NaN,NaN,1124 CR 900 E,NaN,...,NaN,NaN,NaN,,,Quarterly,,1/1/2015,3/31/2015,7/15/2015
1,22970,Friends of Don Gerard,"Adams, George",7/29/2014,500.0,0,NaN,NaN,1124 CR 900 E,NaN,...,NaN,NaN,NaN,,,Quarterly,,7/1/2014,9/30/2014,10/15/2014
2,22970,Friends of Don Gerard,AFL-CIO of Champaign County,3/14/2015,1000.0,0,NaN,NaN,404 W Church St,NaN,...,NaN,NaN,NaN,,,Quarterly,,1/1/2015,3/31/2015,7/15/2015
3,22970,Friends of Don Gerard,AFSCME Illinois,4/1/2015,1000.0,0,NaN,NaN,615 South Second St,NaN,...,NaN,NaN,NaN,,,Quarterly,,4/1/2015,6/30/2015,7/15/2015
4,22970,Friends of Don Gerard,AFSCME Illinois,4/16/2011,1900.0,0,NaN,NaN,615 South Second St,NaN,...,615 South Second St,NaN,Springfield,IL,62701,Quarterly,,4/1/2011,6/30/2011,7/11/2011
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64,22970,Friends of Don Gerard,"Stark, David",4/21/2012,250.0,0,NaN,NaN,1805 W Washington St,NaN,...,NaN,NaN,NaN,,,Quarterly,,4/1/2012,6/30/2012,7/15/2012
65,22970,Friends of Don Gerard,"Stewart, Russell",2/9/2011,250.0,0,NaN,NaN,76 Greencroft,NaN,...,NaN,NaN,NaN,,,Quarterly,,1/1/2011,3/31/2011,4/10/2011
66,22970,Friends of Don Gerard,Teamsters Local Union No. 26,3/23/2015,250.0,0,NaN,NaN,908 N Neil St,NaN,...,NaN,NaN,NaN,,,Quarterly,,1/1/2015,3/31/2015,7/15/2015
67,22970,Friends of Don Gerard,"Turner, James",7/18/2014,1000.0,0,President,O'Brien Auto Park,Brittany Trail,NaN,...,NaN,NaN,NaN,,,Quarterly,,7/1/2014,9/30/2014,10/15/2014
68,22970,Friends of Don Gerard,"Turner, James",2/1/2011,500.0,0,NaN,NaN,Brittany Trail,NaN,...,NaN,NaN,NaN,,,Quarterly,,1/1/2011,3/31/2011,4/10/2011

In [3]:
#extracting date information from date columns
df["RcvdYear"] = pd.DatetimeIndex(data = df["RcvdDate"]).year
df["RcvdMonth"] = pd.DatetimeIndex(data = df["RcvdDate"]).month
df["RcvdDay"] = pd.DatetimeIndex(data = df["RcvdDate"]).day
df

,CommitteeID,CommitteeName,ContributedBy,RcvdDate,Amount,LoanAmount,Occupation,Employer,Address1,Address2,...,VendorState,VendorZip,DocName,Election,RptPdBegDate,RptPdEndDate,FiledRcvdDate,RcvdYear,RcvdMonth,RcvdDay
0,22970,Friends of Don Gerard,"Adams, George",3/18/2015,250.0,0,NaN,NaN,1124 CR 900 E,NaN,...,,,Quarterly,,1/1/2015,3/31/2015,7/15/2015,2015,3,18
1,22970,Friends of Don Gerard,"Adams, George",7/29/2014,500.0,0,NaN,NaN,1124 CR 900 E,NaN,...,,,Quarterly,,7/1/2014,9/30/2014,10/15/2014,2014,7,29
2,22970,Friends of Don Gerard,AFL-CIO of Champaign County,3/14/2015,1000.0,0,NaN,NaN,404 W Church St,NaN,...,,,Quarterly,,1/1/2015,3/31/2015,7/15/2015,2015,3,14
3,22970,Friends of Don Gerard,AFSCME Illinois,4/1/2015,1000.0,0,NaN,NaN,615 South Second St,NaN,...,,,Quarterly,,4/1/2015,6/30/2015,7/15/2015,2015,4,1
4,22970,Friends of Don Gerard,AFSCME Illinois,4/16/2011,1900.0,0,NaN,NaN,615 South Second St,NaN,...,IL,62701,Quarterly,,4/1/2011,6/30/2011,7/11/2011,2011,4,16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64,22970,Friends of Don Gerard,"Stark, David",4/21/2012,250.0,0,NaN,NaN,1805 W Washington St,NaN,...,,,Quarterly,,4/1/2012,6/30/2012,7/15/2012,2012,4,21
65,22970,Friends of Don Gerard,"Stewart, Russell",2/9/2011,250.0,0,NaN,NaN,76 Greencroft,NaN,...,,,Quarterly,,1/1/2011,3/31/2011,4/10/2011,2011,2,9
66,22970,Friends of Don Gerard,Teamsters Local Union No. 26,3/23/2015,250.0,0,NaN,NaN,908 N Neil St,NaN,...,,,Quarterly,,1/1/2015,3/31/2015,7/15/2015,2015,3,23
67,22970,Friends of Don Gerard,"Turner, James",7/18/2014,1000.0,0,President,O'Brien Auto Park,Brittany Trail,NaN,...,,,Quarterly,,7/1/2014,9/30/2014,10/15/2014,2014,7,18
68,22970,Friends of Don Gerard,"Turner, James",2/1/2011,500.0,0,NaN,NaN,Brittany Trail,NaN,...,,,Quarterly,,1/1/2011,3/31/2011,4/10/2011,2011,2,1

In [6]:
df_year = df.groupby("RcvdYear").agg("sum").reset_index()
df_year

,RcvdYear,CommitteeID,Amount,LoanAmount,VendorAddress2,RcvdMonth,RcvdDay
0,2010,68910,2700.00,0,0.0,31,74
1,2011,482370,18485.00,0,0.0,65,249
2,2012,367520,10000.00,0,0.0,84,205
3,2013,22970,500.00,0,0.0,2,4
4,2014,298610,7100.00,0,0.0,82,288
5,2015,344550,16786.76,0,0.0,50,177